### ISSUE TITLE
Appliance to DevTeam of 陈泳琦2020

### ISSUE THREAD

**Issue by revue-starlight** [ThinkSpiritLab/WeNeedYou#15]
---
name: Appliance
about: Template of Appliance to DevTeam in 2020
title: Appliance to DevTeam of $YourName 2020
labels: Appliance
assignees: A0nameless0man, Nugine

---

### 使用的编程语言

|语言|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|C++|4年|算法|应用，可以写课设|
|Free pascal|10年|算法|noip2014_30分|

### 技术栈

|名称|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|Pycharm|3个月|写后端|萌新

## 做过的项目
OTS
## 加入后想做的项目
OJ
## 指向个人主页、博客和/或仓库的链接 （如有）
revue-starlight.github.io
## 其他非你不可的理由
我不会女装

**Comment by Nugine** [comment]
LGTM
