### ISSUE TITLE
Appliance to DevTeam of 杨可 2019

### ISSUE THREAD

**Issue by fitenne** [ThinkSpiritLab/WeNeedYou#16]
---
name: Appliance
about: Template of Appliance to DevTeam in 2020
title: Appliance to DevTeam of 杨可 2019
labels: Appliance
assignees: A0nameless0man, Nugine
---

## 自我介绍

杨可，计算机科学与技术（由自动化转入）专业，现大二。

### 使用的编程语言

|语言|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|C / C++|2年|主力语言，控制台应用程序|应用|
|Python|1年|小工具，数据生成器，系统管理脚本|熟悉|
|html、js|0.5年|简单网页制作|熟悉|
### 技术(栈？)

| 名称     | 时常  | 说明                               |
| -------- | ----- | ---------------------------------- |
| Linux    | 4年   | 桌面平台日常使用、服务器维护       |
| LNMP     | 1年   | 搭建 WordPress                     |
| Git      | 0.5年 | 简单了解过，基本只用来做过版本控制 |
| Qt \ QML | 0.5年 | HelloWorld                         |
| cmake    | 0.5年 | 项目构建                           |

## 做过的项目

做过一个开源 GUI 框架 littlevgl 的移植与 GUI 实现。

二次开发的博客主题。

一些垃圾系统脚本。

## 加入后想做的项目

除了前端的部分。

## 指向个人主页

https://idkduck.xyz/ 

## 其他非你不可的理由

大概无吧。

可能时间比较多。

**Comment by Nugine** [comment]
LGTM
