### ISSUE TITLE
Appliance to DevTeam of 张逸凡 2020

### ISSUE THREAD

**Issue by DKwind1113** [ThinkSpiritLab/WeNeedYou#18]
## 自我介绍

20生态张逸凡
### 使用的编程语言
c++  pascal
|语言|时长|用途|程度|  
|:-:|:-:|:-:|:-:|  
|(举例)C++|4年|主力语言，控制台应用程序|应用|
|(举例)Python|2年|小工具，数据生成器|熟悉|

c++ 熟悉
### 技术栈

|名称|时长|用途|程度|
|:-:|:-:|:-:|:-:|

## 加入后想做的项目
参与学校oj的开发和维护，以后想做一些在线的服务平台
## 其他非你不可的理由
一定的语言基础加上对这方面的热情，以及强烈的兴趣

**Comment by Nugine** [comment]
（小型）在线服务平台更多是商业因素，用到的技术可能十分无聊，也没有多少乐趣。
你对技术本身抱有强烈的兴趣吗？在学习和训练之余，你会花多少时间做自己的项目？

**Comment by DKwind1113** [comment]
1公立的说：&nbsp; 在做职业生涯规划的时候我上阿里的招聘看了一下，程序员相关的岗位过于宽泛，种类非常丰富，为了避免在毕业季迷茫，我觉得我需要多尝试一些。2.就个人兴趣而言：&nbsp; 我有很多的小想法，需要这方面的能力，如果有可能我会去实现。
3就时间安排上：目前光是课业和算法方面的集训仍然有空余时间




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nugine"<notifications@github.com&gt;; 
发送时间: 2020年12月18日(星期五) 晚上8:34
收件人: "ThinkSpiritLab/WeNeedYou"<WeNeedYou@noreply.github.com&gt;; 
抄送: "暗影尘风"<1113465232@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ThinkSpiritLab/WeNeedYou] Appliance to DevTeam of 张逸凡 2020 (#18)





 
（小型）在线服务平台更多是商业因素，用到的技术可能十分无聊，也没有多少乐趣。
 你对技术本身抱有强烈的兴趣吗？在学习和训练之余，你会花多少时间做自己的项目？

**Comment by Nugine** [comment]
@A0nameless0man 我觉得ok

**Comment by Nugine** [comment]
从通知或邮件里可以看到邀请，接受后就能加入组织了。
