### ISSUE TITLE
Appliance to DevTeam of yinhuaxiang 2020

### ISSUE THREAD

**Issue by Shirandechengzhangzhilu** [ThinkSpiritLab/WeNeedYou#19]
## 自我介绍

殷化翔 2019级 地理信息科学
C语言程序设计99分，计算机等级考试优秀，两次校赛二等奖

## 技能
> 1. 会一点点html、CSS、JS，参加过共享杯（铁）
> 2. 喜欢写知乎、喜欢写博客、喜欢学习新事物
> 3. 学会一点点markdown

### 使用的编程语言

|语言|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|C++|1年|抄一些有趣的代码；控制台应用程序|应用|
|Python|1年|小工具，会一些语法，会用一些Python模块|熟悉|
|MATLAB| 1年| 参加过数模|熟练|
|C# |0.5年| 会一些简单的控制台和窗体应用 |了解|
|HTML、CSS|1年| 参加比赛| 了解|

### 技术栈

|名称|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|AE|1年 |剪辑视频，发公众号，做部门的总结视频 |了解|
|PR|1年|剪辑视频，发公众号，做部门的总结视频 |熟悉|
|arcgis|0.5年|专业课软件，画图和二次开| 熟练|
|MATLAB|1年|数值运算|应用|

## 做过的项目
 抄别人代码算嘛....（虽然是手打的，画过中秋月饼，写过一些小游戏）

## 加入后想做的项目
> 1. 毕业后想做gis二次开发方向，想学习和二次开发有关的内容
> 2. 先从比较简单的内容开始学习
> 3. 人工智能和神经网络（可有可无，打算寒假自己自学，觉得非常有用）
> 4. 想要学习Latex语法，方便文章的排版

## 指向个人主页、博客和/或仓库的链接 （如有）
 https://blog.csdn.net/matlab2020ab?t=1
 写过50篇水文.........根本不值一提

## 其他非你不可的理由
感觉大佬很多，想尝试一下开发组，可以学到很多的知识，和自己未来的就业方向也有一定的关系。
 热衷于学习新知识，喜欢计算机方面的编程，希望服务于更多的同学，不虚度自己的青春年华。
 大二下学期打算冲击蓝桥杯省二和数模国赛，高数省三已凉。下学期课程数量很少，非常适合学习新知识和竞赛
可以协调好自己的时间，大一获得过省级及校级奖项15余项，综测排名和专业排名前三，获得过三好学生标兵
 下学期会开设数据库原理的课程

**Comment by Shirandechengzhangzhilu** [comment]
> ## 自我介绍
> 殷化翔 2019级 地理信息科学
> C语言程序设计99分，计算机等级考试优秀，两次校赛二等奖
> 
> ## 技能
> > 1. 会一点点html、CSS、JS，参加过共享杯（铁）
> > 2. 喜欢写知乎、喜欢写博客、喜欢学习新事物
> > 3. 学会一点点markdown
> 
> ### 使用的编程语言
> 语言	时长	用途	程度
> C++	1年	抄一些有趣的代码；控制台应用程序	应用
> Python	1年	小工具，会一些语法，会用一些Python模块	熟悉
> MATLAB	1年	参加过数模	熟练
> C#	0.5年	会一些简单的控制台和窗体应用	了解
> HTML、CSS	1年	参加比赛	了解
> ### 技术栈
> 名称	时长	用途	程度
> AE	1年	剪辑视频，发公众号，做部门的总结视频	了解
> PR	1年	剪辑视频，发公众号，做部门的总结视频	熟悉
> arcgis	0.5年	专业课软件，画图和二次开	熟练
> MATLAB	1年	数值运算	应用
> ## 做过的项目
> 抄别人代码算嘛....（虽然是手打的，画过中秋月饼，写过一些小游戏）
> 
> ## 加入后想做的项目
> > 1. 毕业后想做gis二次开发方向，想学习和二次开发有关的内容
> > 2. 先从比较简单的内容开始学习
> > 3. 人工智能和神经网络（可有可无，打算寒假自己自学，觉得非常有用）
> > 4. 想要学习Latex语法，方便文章的排版
> 
> ## 指向个人主页、博客和/或仓库的链接 （如有）
> https://blog.csdn.net/matlab2020ab?t=1
> 写过50篇水文.........根本不值一提
> 
> ## 其他非你不可的理由
> 感觉大佬很多，想尝试一下开发组，可以学到很多的知识，和自己未来的就业方向也有一定的关系。
> 热衷于学习新知识，喜欢计算机方面的编程，希望服务于更多的同学，不虚度自己的青春年华。
> 大二下学期打算冲击蓝桥杯国二和数模国赛，高数省三已凉。下学期课程数量很少，非常适合学习新知识和竞赛
> 可以协调好自己的时间，大一获得过省级及校级奖项15余项，综测排名和专业排名前三，获得过三好学生标兵
> 下学期会开设数据库原理的课程

**Comment by Nugine** [comment]
看起来可以。
原则上开发组成员从算法组中选拔，20级招新完毕后，我们会根据具体情况决定是否通过。

**Comment by Shirandechengzhangzhilu** [comment]
好的，谢谢你们，感谢你们长期以来对我校online judge的维护。我大下学期只有二4门课程，分别是：英语、数据结构、数字高程模型还有遥感原理。课外时间就会比较多，如果你们缺人我非常乐意学习新的知识，加入你们，期待你们能够在icpc比赛中为我校获得更多的奖牌。

**Comment by Shirandechengzhangzhilu** [comment]
请问一下招新完毕啦嘛，寒假已经过半咯

**Comment by Nugine** [comment]
不好意思耽搁了。考虑到选拔策略的因素，我们讨论后决定不通过此申请。
你仍然可以按照流程参与我们的开源项目，代码和设计都是开放的，我们欢迎来自任何人的贡献。
