### ISSUE TITLE
Appliance to DevTeam of 李嘉松 2021

### ISSUE THREAD

**Issue by aNewboya** [ThinkSpiritLab/WeNeedYou#20]
## 自我介绍

李嘉松，计算机科学与技术，18
### 使用的编程语言

|语言|时长|用途|程度|
|:-:|:-:|:-:|:-:|
C/C++|半年|主力语言，算法|应用
hmtl，CSS|半个月|随便写写网页|了解
Go|几天|写算法||熟悉
|Python|1个月||了解|

### 技术栈
CentOS
Ubuntu

|名称|时长|用途|程度|
|:-:|:-:|:-:|:-:|

## 加入后想做的项目
维护后端

**Comment by aNewboya** [comment]
https://gitee.com/anewboya
提交的代码只有算法题，最近的都没有交

**Comment by flaryer** [comment]
简历写的有点随意。
