### ISSUE TITLE
Appliance to DevTeam of 张旨涵 2022

### ISSUE THREAD

**Issue by Deseer** [ThinkSpiritLab/WeNeedYou#28]
## 自我介绍

张旨涵，数据科学与大数据技术，18
## 技能
会修机，有很多修机工作经历
### 使用的编程语言

|语言|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|Python|2年|主力语言，网络爬虫，mongodb数据库|熟悉|
|Java|1年|感兴趣学习过|应用|
|html|半年|爬虫需要|了解|

### 技术栈
Ubuntu

|名称|时长|用途|程度|
|:-:|:-:|:-:|:-:|

## 做过的项目/深度参与的课设
部分网站的爬虫爬取
## 加入后想做的项目

希望能加入维护前后端的行列，学习下更多关于网站的知识

**Comment by bkmashiro** [comment]
留个联系方式, 或者发个邮件给join_spirit_lab@yuzhes.com, 稍后联系你. @Deseer

**Comment by bkmashiro** [comment]
已经通过邮箱联系您。如果没有收到消息，请电邮 issue@yuzhes.com 并备注id.
