### ISSUE TITLE
Appliance to DevTeam of 黄海天 2022

### ISSUE THREAD

**Issue by YOMIZU** [ThinkSpiritLab/WeNeedYou#29]
## 自我介绍
黄海天，22级计算机类，18。
爱好体育运动，如健身，长跑，骑行，有体力劳动的话就交给我了。
目前在专业能力上确实有所不足，但会通过今后的学习加以改进，使自己能确实地在团队中起到作用，为同学们服务。
这份申请可能有些单薄，但我想要在这样一个团队中提升自己的想法是真实的。

### 使用的编程语言

|语言|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|C语言|1年|主力语言|熟悉|
|C++|初步开始学习|拓展能力|了解|

### 技术栈

|名称|时长|用途|程度|
|:-:|:-:|:-:|:-:|

## 加入后想做的项目

自己对程序设计，维护系统较感兴趣，想要在积累基础能力之后参与维护学校的OJ系统，又或者参与开发新的功能，借此磨练自身

**Comment by bkmashiro** [comment]
已经通过邮箱联系您。如果没有收到消息，请电邮 issue@yuzhes.com 并备注id.
