### ISSUE TITLE
Appliance to DevTeam of 吴天一 2022

### ISSUE THREAD

**Issue by faithleysath** [ThinkSpiritLab/WeNeedYou#30]
## 自我介绍
我叫吴天一，2022级数据科学与大数据技术的本科生（想转计科），思维敏捷，学习能力较强，专业排名靠前。爱好折腾。

初二参加过NOIP，有C++基础。

### 使用的编程语言

|    语言    | 时长  |                             用途                             | 程度 |
| :--------: | :---: | :----------------------------------------------------------: | :--: |
|    C++     |  2年  | 做题用，控制台应用程序（写过五子棋）目前在看《C++ Primer Plus》进度40% | 应用 |
|   Python   |  1年  |    小工具，爬虫，数据处理，GUI程序（tkinter），Django框架    | 应用 |
|    Java    |  1年  |                  爬虫，Web开发（跟课学习）                   | 熟悉 |
| html5/css3 | 0.5年 |                    在学，会简单页面的制作                    | 熟悉 |
| Bash Shell | 0.5年 |                       会改其他人的脚本                       | 了解 |

### 技术栈

|   名称   | 时长  |                           用途                            | 程度 |
| :------: | :---: | :-------------------------------------------------------: | :--: |
|  修电脑  |  3年  |                       解决软硬问题                        | 精通 |
| Markdown |  3年  |                          记笔记                           | 熟练 |
|  Latex   |  2年  | 写[数学文章](https://www.zhihu.com/people/leayn-86/posts) | 应用 |
|  Ubuntu  |  1年  |                     会一些基本的命令                      | 应用 |
|   Git    | 半年  |                         版本管理                          | 应用 |
|   宝塔   | 半年  |                Vultr上在用，搭了一个Alist                 | 熟悉 |
|   Vim    | 半年  |                        会基本操作                         | 了解 |
|  Vaadin  | 半年  |                    Java Web框架，用过                     | 了解 |
|  软路由  | 半年  |                           多拨                            | 在用 |
|  Grub2   | 1个月 |                        引导多系统                         | 在学 |

## 做过的项目/深度参与的课设

- 高中时用Python开发过一个“PPT语音翻页工具"的GUI程序
- 编程游戏《异常》通关😂
- 《Turing Complete》游戏中用**基本电路**搭出了一个**”图灵完备“**的计算机

## 加入后想做的项目
维护后端

## 指向个人主页、博客和/或仓库的链接（如有）

- Github主页：https://github.com/faithleysath
- 知乎主页：https://www.zhihu.com/people/leayn-86

## 其他非你不可的理由

兴趣浓厚吧。

**Comment by bkmashiro** [comment]
挺好

**Comment by bkmashiro** [comment]
同学留个联系方式, 或者发个邮件给join_think_spirit@yuzhes.com, 稍后联系你哈 @faithleysath

**Comment by bkmashiro** [comment]
已经通过邮箱联系您。如果没有收到消息，请电邮 issue@yuzhes.com 并备注id.
