### ISSUE TITLE
Appliance to DevTeam of Dustella 2020

### ISSUE THREAD

**Issue by Dustella** [ThinkSpiritLab/WeNeedYou#31]
## 自我介绍

2020 级的 特菈 Dustella，一个普通的前端开发者。爱好写诗。

### 使用的编程语言

|语言|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|C++|2年|非主力语言，写题用|了解|
|Python|3年|主力语言之一。一般用来写脚本或者做数据分析，也耍过`Flask`|熟练|
|TypeScript|2年|最常使用的语言。用于各种前端和后端开发|熟练|
|Golang|1年半|仅仅用于写后端用。做过一个校园网登陆|应用|
|Rust|半年|纯粹是玩的，写过一个语法分析器、若干玩具|熟悉|
|C#|三年|但是两年没碰过，最开始写机器人用的|了解|

### 技术栈

|名称|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|Vue2和Vue3|两年半|各种前端开发，写过无数次|精通|
|solidjs|半年|个别前端项目的开发，做过具体应用|熟练|
|Ubuntu|五年|这是我最常在服务端环境用的发行版|熟悉|
|Docker|三年|擅长将服务容器化并且配置CICD|熟练|
|Postgresql|一年|我用的关系型数据库|熟悉|
|MongoDb|一年|我喜欢的非关系型数据库，用的比上面多|熟悉|
|express|一年|用它写过后端|熟悉|
|gin|一年|用它写过后端|熟悉|
|springboot|一年|拿它写过后端|了解|

## 做过的项目/深度参与的课设

*  在 [迈趣儿科技有限公司](https://maiquer-landingpage-3ctqbc3d7792-1309603781.ap-shanghai.app.tcloudbase.com/) 参与研发四个项目的前端、一个外包项目的前端。
*  一个 [大葱云打水第三方客户端](https://github.com/Dustella/green-orion-water-api)，基于 Nodejs 实现了部分协议。独立完成。
*  给 [多火互联网工作室](https://www.duohuo.org.cn) 写了个主页，使用 Astro 框架。就是这个链接。和我对象一起写的。
*  使用 [Rust 实现的语法分析器](https://github.com/Dustella/negatives)。独立完成。
*  一个 [基于 Nonebot 的 QQ 机器人](https://github.com/Dustella/Charlottebot)。独立完成。
*  各式各样的玩具，例如各种基于Worker的API、乱七八糟的demo、还有一个主题，请参阅 [我的仓库](https://github.com/Dustella?page=3&tab=repositories)

## 加入后想做的项目

现有的 OJ 系统相对于别的学校的已经相当完善了，我觉得可能主要是解决一些 UX 问题和 debug？

非常希望可以接到新的需求

## 指向个人主页、博客和/或仓库的链接

[我的站点](https://dustella.net) 自制的轻改 vitepress 主题

[我的仓库](https://github.com/Dustella?page=3&tab=repositories)

## 其他非你不可的理由

并没有

### 留个邮箱

`me@dustella.net`

**Comment by bkmashiro** [comment]
本年度最强
