### ISSUE TITLE
Appliance to DevTeam of 徐博文 2021

### ISSUE THREAD

**Issue by ROMYSTIQUE** [ThinkSpiritLab/WeNeedYou#33]
## 自我介绍
徐博文，21级计算机科学与技术，半个算竞选手吧

### 使用的编程语言

|语言|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|C/C++|1年半|主力语言，算竞使用语言|搞算竞语法和STL还是熟练的；面向对象部分用的少，了解|
|JAVA|1个月（在学）|开发入门|了解|
|C#|1个月（在学）|数据库课设使用|了解|

### 技术栈

|名称|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|Markdown|1年|做笔记，文本编辑|熟练|
|LaTeX|1年|数学公式、文章等|熟练|
|PS（gimp）|1年半|修图、简单图像海报合成和UI设计（gimp有段时间没用了）|熟练|
|git|1个月（在学）|历史版本管理|了解|
|SQL  server/MySQL|1个月（在学）|简单数据库操作和管理|熟悉|

## 做过的项目/深度参与的课设

没什么项目经验，课设的话学校课程里布置的算吗ヽ(´～｀；)（高校学生管理系统，模式匹配算法应用，基于机器学习的树叶形状分类器，感觉没啥技术含量。。）

## 加入后想做的项目

前端？感觉前端和UI平面有点关系奥，个人对设计感兴趣，不过做什么我都不介意（如果可以）

最主要还是希望能扩充开发方面的技能，具备一定独立开发能力（毕竟只搞算竞真的没啥项目开发经验T^T，希望以后二者能相辅相成吧）

## 指向个人主页、博客和/或仓库的链接（如有）

暂无

### 留个邮箱

1395711160@qq.com

**Comment by bkmashiro** [comment]
已通过邮箱联系您. 如未收到请邮 issue@yuzhes.com .
