### ISSUE TITLE
Appliance to DevTeam of  LIFE-SI  2021

### ISSUE THREAD

**Issue by LIFE-SI** [ThinkSpiritLab/WeNeedYou#34]
## 自我介绍

名字： $LIFE-SI$ 

专业：计算机科学与技术

目前状态：很闲

## 技能

| 一些没用的技能 |  时长   | 用途                         | 程度 |
| :----: | :-----: | :---------------------------: | :--: |
| C/C++  | 2 year  | 写题、课设                    | 应用 |
| python | 3 month | 数据分析/数据可视化，数模 | 熟悉 |
| Java   | 1 month | 课设                          | 了解 |
| Markdown | 2 year  | 笔记 | 熟练 |

## 参与过

有幸参与南理工 $21$ 级新生部分学院的网页设计和编写（南理大佬带我）
一些比较水的课设
仓库放的都是一些 $OJ$ 上的算法题和一些未公开的文件资料
## 加入后

后端开发，系统维护
（主要是想寻找一个契机，尝试学习新东西）

### 联系方式：

[life_si@163.com](mailto:life_si@163.com)

**Comment by bkmashiro** [comment]
已通过邮件联系你.
