### ISSUE TITLE
Appliance to DevTeam of 张亮鹏 2022

### ISSUE THREAD

**Issue by zhanglp0129** [ThinkSpiritLab/WeNeedYou#35]
## 自我介绍
- 张亮鹏，2022级，计算机类专业，19岁
- 喜欢编程，写代码使我快乐
- 喜欢研究算法，会坚持在[力扣](https://leetcode.cn/u/zhanglp0129/)上刷题

### 使用的编程语言

|语言|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|C语言|2年|我最早接触的编程语言，现在不怎么用了|熟练|
|C++|半年|主力语言，用于竞赛等，我的一些项目用的也是C++|应用|
|Java|半年|Web后端开发|熟悉|
|python|1年|主要用来写写爬虫，还有小工具|了解|
|html/css/javascript|半年|前端三件套，主要用来写写网页的前端页面|了解|

### 技术栈

|名称|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|markdown|半年|写笔记比较方便|应用|
|CentOS|半年|Linux操作系统，用来搭建服务器|熟悉|
|SSH|半年|服务器远程控制软件。虽然有更好用的，但我还是喜欢用自带的SSH服务|应用|
|MySQL|半年|基本的增删改查我还是会的|熟悉|
|gcc/g++|1年|体验一下记事本编程是什么感受，而且配置VSCode要用这个|了解|
|nginx|半年|用于反向代理，会抄一些网上的配置|了解|

## 做过的项目/深度参与的课设
- 我用C++的easyx库写过一个五子棋游戏，可是代码被不小心我删了
- 有一段时间非常喜欢玩原神，就写了一个[原神抽卡模拟器](https://github.com/zhanglp0129/YsWish)，当然现在烂尾了

## 加入后想做的项目
- 维护后端以及评测系统
- 我想优化一下OJ的评测系统。之前我做OJ的时候，经常出现，明明做对了，但就是不给过的情况，所以我的正确率一直很低
- 主要还是想学习一下技术，锻炼一下自己

## 指向个人主页、博客和/或仓库的链接（如有）
- [github仓库](https://github.com/zhanglp0129)
- [LeetCode主页](https://leetcode.cn/u/zhanglp0129/)

## 其他非你不可的理由
- 一颗热爱编程，热爱开发的心
- 能够不断学习新技术

### 留个邮箱
邮箱：zhanglp0129@gmail.com

**Comment by bkmashiro** [comment]
已透过电邮联络你.
