### ISSUE TITLE
Appliance to DevTeam of $张涵聪 2021

### ISSUE THREAD

**Issue by pluto-han** [ThinkSpiritLab/WeNeedYou#36]
## 自我介绍

张涵聪， 21计科

热爱游戏，以及一切新知识

~~还有我家哥哥~~

### 使用的编程语言

|    语言    | 时长 | 程度 |                   用途                   |
| :--------: | :--: | :--: | :--------------------------------------: |
|    C++     | 2年  | 熟练 |       主力语言，用于写题，写小项目       |
|   Python   | 一年 | 应用 |  转正主力途中，用于写深度学习，一些脚本  |
| TypeScript | 半年 | 了解 |            在学，做一些小脚本            |
|    java    | 一年 | 了解 | 觉得挺有用的，学了点，做了个坦克大战游戏 |

### 技术栈

|  名称  |  时长  |          用途          | 程度 |
| :----: | :----: | :--------------------: | :--: |
| Ubuntu |  一年  |     在虚拟机上玩过     | 了解 |
| mysql  | 两个月 |        上课学的        | 了解 |
| matlab | 一年半 | 打数模，偶尔用来画个图 | 应用 |

## 做过的项目/深度参与的课设

c++课设：学生管理系统

参与过得深度学习项目：VGG, ResNet 搭建

正在做：copy-move detection

## 加入后想做的项目

还没有想好，大概是维护后端吧()

## 指向个人主页、博客和/或仓库的链接（如有）

[[pluto-han (Mark Cheung) (github.com)](https://github.com/pluto-han)](https://github.com/pluto-han)

几乎没东西()

## 其他非你不可的理由

不摆烂。菜，但是乐于接受新知识

### 留个邮箱

[1514142997@qq.com](mailto:1514142997@qq.com)

**Comment by bkmashiro** [comment]
已透过邮箱联系您。如果没有收到消息，请电邮 issue@yuzhes.com
