### ISSUE TITLE
Appliance to DevTeam of 北雁云依 2020

### ISSUE THREAD

**Issue by BeiyanYunyi** [ThinkSpiritLab/WeNeedYou#37]
## 自我介绍

2020 级 北雁云依，大气科学（气象学）专业，@Dustella 的女友，休学准备手术的 MtF。爱好很杂：会念左经，读过庄子，喜欢福柯，焊过电路，炸过酒精，写写全栈。

缺点大概是完全没有学过计算机专业课程，数据结构、算法、编译原理这些基本功极烂，只能写写业务代码维持生计的样子。

### 使用的编程语言

|语言|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|JavaScript/TypeScript/HTML/CSS|2 年|主力语言，前端开发|熟练|
|C|? 年|考试|了解|
|Pascal|7 年|半途而废的 OI|了解|
|Fortran90|1 年|考试|了解|
|Rust|1 年|当脚本用|应用|
|Go|1 年|写服务端|应用|
|Python|半年|科学计算|应用|
|Dart|半年|使用 Flutter 编写跨端图形应用|熟练|
|Kotlin|0|在玩|了解|

### 技术栈

|名称|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|Ubuntu|11 年|操作系统|我不到啊|
|ArchLinux|5 年|操作系统|不知道|
|宝塔|5 年|服务器面板，但是狗都不用|应用|
|nginx|5 年|反向代理、静态资源服务|应用|
|React|2 年|前端开发|熟练|
|Vue3|1 年|前端开发|熟练|
|SolidJS|1 年|前端开发|熟练|
|tailwindcss、windicss、UnoCSS|1 年|CSS 框架|~~事开发者~~|
|Nuxt3|半年|全栈开发|应用|
|Express|两年|写后端|熟练|
|Fastify|一年|写后端|熟练|
|Astro|半年|写博客和静态网页|熟练|
|MongoDB|2 年|数据库|熟练|
|Redis|1 年半|数据库|应用|
|MySQL|1 年半|数据库|应用|
|SQLite|1 年半|数据库|应用|
|PostgreSQL|1 年半|数据库|应用|

## 做过的项目/深度参与的课设

- ~~[UnoCSS](https://github.com/unocss/unocss) 类似 tailwindcss 的 CSS 框架，只做了一点微小的贡献~~
- [Icalingua](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus) ~~马上就要完蛋的~~第三方 QQ 客户端，我作为曾经的第二作者，负责了其中 Redis 和三大开源 SQL 数据库的驱动
- [totoroschool-autorun](https://github.com/BeiyanYunyi/totoroschool-autorun) 基于中间人攻击的龙猫校园自动跑项目，使用 NodeJS
- [totoro-paradise](https://github.com/BeiyanYunyi/totoro-paradise) 基于微信扫码的龙猫校园自动跑项目，使用 Nuxt3
- [solid-toast](https://github.com/ardeora/solid-toast) 给 SolidJS 用的 toast 库，我改善了它的逻辑与封包体积
- [bilibili_subscriber](https://github.com/BeiyanYunyi/bilibili_subscriber) 因为 B 站账号被封而写，提供不依赖于 B 站关注功能的关注功能
- [Astro-Blog-Lithium](https://github.com/BeiyanYunyi/Astro-blog-Lithium) 使用 Astro 糊的博客
- [BookExchange](https://github.com/BeiyanYunyi/BookExchange) 为读书日易书活动而快速成型（10 天）的全栈工程，技术栈为 Express+Vue3+NaiveUI
- [sodesu](https://github.com/BeiyanYunyi/sodesu) waline 评论系统的第三方前端
- [炎上书屋](https://firebook.store) 东方 project 网文网站，负责了整个前端的编写，技术栈为 Vue3，界面设计不是我做的，别打我

剩下的看我 GitHub 页面就好，除了炎上书屋以外都是开源项目，自己写的东西都会拿 AGPL3 开源出来。

## 加入后想做的项目

维护前端，和男票一起动动后端

## 指向个人主页、博客和/或仓库的链接（如有）

[仓库](https://github.com/BeiyanYunyi)

[个人主页](https://me.penclub.club)

[博客](https://stblog.penclub.club)

## 其他非你不可的理由

男票刚进去

### 留个邮箱

已单独发送

**Comment by bkmashiro** [comment]
已透过邮箱联系您。如果没有收到消息，请电邮 issue@yuzhes.com
