### ISSUE TITLE
Appliance to DevTeam of 王志和 2021

### ISSUE THREAD

**Issue by littlewith** [ThinkSpiritLab/WeNeedYou#38]
## 自我介绍
来自软件学院，2021级，然后对开发感兴趣，然后......没了，队长请往下看。

## 技能
1.（应该是会）前端开发：html+css+javascript(typescript)三件套，熟练使用vue框架、bootstrap框架、axios（Ajax）。
2.（应该能会）后端开发：python--flask、django框架；go--gin、net.http包、tcp和udp编程；Java--spring、tomcat技术栈；node.js开发、php--thinkphp框架。
3.（应该也会）中间件：tomcat、nginx、apache、lnmp、lamp集成件、宝塔面板、phpstudy面板
4.（应该用过）数据库：redis、mssql、mysql
### 使用的编程语言

|语言|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|C/C++|2年|偏向于底层，控制台应用程序，Windows api调用|熟悉|
|Python|3年|小工具，数据生成器，编码解码器、爬虫、自动化运维、后端开发|应用|
|javascript(Typescript)|2年|网页脚本、前端开发、node.js服务端开发|熟悉|
|Golang|2年|后端开发、tcp/udp网络编程|应用|
~Rust、Java，算了，还是暂时先写上面这些吧，还在打怪升级中~

### 技术栈

1.是Linux系统小菜鸡：ubuntu、debian、fedora，ssh、nginx、IP tables等小东西
2.略懂网络安全：top 10漏洞，漏洞利用和防范方法
## 做过的项目/深度参与的课设
* 队长可见我的个人主页或者仓库
github.com/littlewith
## 加入后想做的项目

都想做，能做什么就做什么吧。
## 指向个人主页、博客和/或仓库的链接（如有）
* 个人主页: home.littlewith.top （前后端都手工敲，累麻了已经，主页有我的一些小作品啥的）
* 博客: littlewith.github.io（看心情，发博客）
## 其他非你不可的理由
* 我想来玩玩。
* 我会讲笑话。
* 我会吃饭，会睡觉，身体健康，开开心心，嘻嘻哈哈。
### 留个邮箱
andytoe@littlewith.top
andytoe@qq.com

**Comment by bkmashiro** [comment]
已透过 andytoe@littlewith.top 联络你.
