### ISSUE TITLE
Appliance to DevTeam of 黄翔 2022

### ISSUE THREAD

**Issue by PlumeSheep** [ThinkSpiritLab/WeNeedYou#39]
## 自我介绍
2022级，计算机学院，优点：暑假时间多，缺点：没有相关经验，爱好：玩游戏

### 使用的编程语言

|语言|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|C语言|1年不到|完成oj题目|熟悉|
|C++|1年不到|能看懂部分|了解|

### 技术栈

|名称|时长|用途|程度|
|:-:|:-:|:-:|:-:|

## 加入后想做的项目

希望oj系统越来越好
## 其他非你不可的理由
想要学习点有用的知识，找到自己未来前进的方向，防止大学虚度时光
### 留个邮箱
1136959728@qq.com
这很重要. 为了让我们能方便的联系到你.
为了保护隐私, 你可以邮将此issue的地址和你的信息发送到join_think_spirit@yuzhes.com, 我们会单独核实

**Comment by bkmashiro** [comment]
已透过邮件联系你.
