### ISSUE TITLE
Appliance to DevTeam of Flaryer 2020

### ISSUE THREAD

**Issue by Flaryer** [ThinkSpiritLab/WeNeedYou#4]
## 自我介绍

张兴洋 计算机类 2019级  
## 技能
1. 会~~偷源码造站~~，会造个博客，略加维护  
2. 会宝塔基础，linux命令行基础，nginx基础，会~~搭梯子~~  
3. 会~~重装系统~~  
### 使用的编程语言
C/C++  
|语言|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|C++|1年|控制台应用程序|应用|   

~~HTML/Bootstrap看过一遍，没有训练，差不多忘记了，PHP看了几节就放弃了（没时间）~~

### 技术栈

|名称|时长|用途|程度|
|:-:|:-:|:-:|:-:|

~~会安装ps pr算吗~~
## 做过的项目
~~无~~
## 加入后想做的项目
~~希望由浅入难，虽然好奇心很大，但是我知道我很菜~~  
## 指向个人主页、博客和/或仓库的链接 （如有）
[博客](https://flary.top:444)  
~~还有一些偷来的站~~
## 其他非你不可的理由
~~我，我能折腾~~
~~用删除线是因为没脸了，强行凑字，tcl~~

**Comment by Nugine** [comment]
我觉得可以。
@A0nameless0man

**Comment by A0nameless0man** [comment]
1.  宝塔，Linux，牛轧糖之类的也算技术栈。
1. 可以的
@Flaryer @Nugine
