### ISSUE TITLE
Appliance to DevTeam of $黄奕斌 2021

### ISSUE THREAD

**Issue by ywsaer** [ThinkSpiritLab/WeNeedYou#41]
## 自我介绍
21级计算机科学与技术黄奕斌

### 使用的编程语言

|语言|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|C++|1年|主力语言，算法，控制台应用程序|应用|
|Python|1年|小工具，爬虫，数据生成器|应用|
|Java|半年|写数据库课设|应用|

### 技术栈

|名称|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|MySQL/SQL serve|半年|写课设需要|应用|
## 做过的项目/深度参与的课设
c++课设
Python飞机小游戏
## 加入后想做的项目

维护系统

## 其他非你不可的理由
菜的同时愿意进入新环境学习东西
### 留个邮箱
321201988@qq.com

**Comment by bkmashiro** [comment]
已经用邮件联系你。
