### ISSUE TITLE
Appliance to DevTeam of WEORIGIN 2022

### ISSUE THREAD

**Issue by WEORIGIN** [ThinkSpiritLab/WeNeedYou#42]
NUIST 20 级 计算机科学与技术 
马上就大四了，by设计有些许想法，主要想来学习学习，看看从大一开始折磨我们的OJ系统是怎么做的（哈哈bushi）
虽然可能不会有很突出的贡献，但是希望可以进入团队了解一下。
由于还有一年就要离开南信大，并且本人比较内向一些，个人信息就不过多透漏了。
最后，再次希望Think Spirit Lab团队可以接收我。

---
我的邮箱 ：weorigin@163.com

**Comment by bkmashiro** [comment]
已经通过邮件联系你.
