### ISSUE TITLE
Appliance to DevTeam of 汤范博文 2022

### ISSUE THREAD

**Issue by TFboy1** [ThinkSpiritLab/WeNeedYou#43]
自我介绍
2022级计算机院汤范博文，喜欢唱跳rap蓝球（划掉）

技能
使用的编程语言
语言	时长	用途	程度
Java	6个月	Web开发 熟悉
JavaScript 6个月 web开发前端 熟悉
技术栈
名称	时长	用途	程度
node.js	6个月	Web前端开发	应用
Spring Boot 3个月	web后端开发	了解
做过的项目/深度参与的课设

加入后想做的项目
前后端都可以，前端已经学完三件套，后端马上也能学完

其他非你不可的理由
我非常热爱编程，并且一直致力于提高自己的技术水平。我相信，加入贵项目组可以让我更好地锻炼自己，学习更多的知识和技能，并且为项目组的发展做出自己的贡献，且本人擅长灵活使用各类AI工具。
留个邮箱
1139500183@qq.com

**Comment by bkmashiro** [comment]
已拉进群.
