### ISSUE TITLE
Appliance to DevTeam of $YourName 2022

### ISSUE THREAD

**Issue by zhuyu-xuan** [ThinkSpiritLab/WeNeedYou#44]
## 自我介绍
朱宇轩 21级经管院大数据管理与应用 20岁 非计算机专业 但是对编程感兴趣 后悔当初没转. 主要想来学习如何应用学到的语言基础

### 使用的编程语言

|语言|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|Java|2年|编程入门语言,专业原因使用较少|熟悉|
|Python|2年|平时专业内主要使用的语言,用的比较熟练|应用|
|C/C++|不足半年|为了考研学习的C/C++,语法基本了解,C++了解到了泛型和模板,但是没有接触太多的库|了解|

### 技术栈

|名称|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|CentOS|一学期|用来学习Linux|大概学完了RHCSA的内容,了解基本的常用指令|
|MySQL|一学期|课程学习用|没有实际应用过,学习的是基本语法|
|Vue|一学期|课外补充|学过一些,但是很久没用了

## 做过的项目/深度参与的课设
目前没有参加过的计算机相关的项目

## 加入后想做的项目

目前只接触到了语言基础,没有应用机会,想借此机会学习应用一下,想要看看项目后端是什么样子,以后想要尝试后端相关的工作
## 其他非你不可的理由
留下我可以给大家找好康的
### 留个邮箱
1104334960@qq.com
这很重要. 为了让我们能方便的联系到你.
为了保护隐私, 你可以邮将此issue的地址和你的信息发送到join_think_spirit@yuzhes.com, 我们会单独核实

**Comment by bkmashiro** [comment]
已通过邮件联系你.

**Comment by zhuyu-xuan** [comment]
okk
