### ISSUE TITLE
阿巴阿巴阿巴巴

### ISSUE THREAD

**Issue by Snoozywqe** [ThinkSpiritLab/WeNeedYou#45]
## 自我介绍
(你可以不写隐私信息.)

杜浩，计算机类，19，感觉没什么优点全是缺点，对信息安全感兴趣，密码和pwn的兴趣高QAQ
### 使用的编程语言
C++，python，一点点js
|语言|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|(举例)C++|4年|主力语言，控制台应用程序|应用|
|(举例)Python|2年|小工具，数据生成器|熟悉|

C++ 1年 主力语言 了解
python 半年 了解
### 技术栈

|名称|时长|用途|程度|
呜呜呜这都是啥啊我只认识个MySQL

## 加入后想做的项目

开发，开发，开发！！！
## 指向个人主页、博客和/或仓库的链接（如有）

https://blog.csdn.net/cptcpt_/article/details/139245439

### 留个邮箱
838009959@qq.com
这很重要. 为了让我们能方便的联系到你.
为了保护隐私, 你可以邮将此issue的地址和你的信息发送到join_think_spirit@yuzhes.com, 我们会单独核实

**Comment by bkmashiro** [comment]
👏👏👏
