### ISSUE TITLE
Appliance to DevTeam of $YourName 2023

### ISSUE THREAD

**Issue by Sandy-wxy** [ThinkSpiritLab/WeNeedYou#46]
## 自我介绍
(你可以不写隐私信息.)

### 使用的编程语言

|语言|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|(举例)C++|4年|主力语言，控制台应用程序|应用|
|(举例)Python|2年|小工具，数据生成器|熟悉|

### 技术栈

|名称|时长|用途|程度|
|:-:|:-:|:-:|:-:|

### 留个邮箱
这很重要. 为了让我们能方便的联系到你.
为了保护隐私, 你可以邮将此issue的地址和你的信息发送到join_think_spirit@yuzhes.com, 我们会单独核实

**Comment by qwertycxz** [comment]
哥们简历就写两行？
