### ISSUE TITLE
Appliance to DevTeam of 王欣悦 2023

### ISSUE THREAD

**Issue by Sandy-wxy** [ThinkSpiritLab/WeNeedYou#47]
## 自我介绍
姓名：王欣悦
专业：软件工程
年级：23级
MBTI：infp小蝴蝶
爱好：敲算法题
优点：心态比较好（VScode装了40多天，什么bug都出现过）
缺点：心态比较好

### 使用的编程语言

|语言|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|C/C++|1年|主力语言，写各大网站的算法题|应用|
|Java|n个月|前后端，打打蓝桥杯|了解|
|py|1个星期|写脚本，GPT协助|了解|

### 技术栈

|名称|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|Chatgpt 4o|1学期|解决各种技术问题|熟练|
## 做过的项目/深度参与的课设  
 百科园系统（emm是期末大作业）

## 加入后想做的项目     
暑假打算开发个小app、小游戏2468或者植物大战僵尸。
OJ的话：想开发一个像codeforces那种赛制，月赛之类的。

## 指向个人主页、博客和/或仓库的链接（如有）
有，但是里面没啥东西：CSDN，博客园，知乎
## 其他非你不可的理由
无，随时可踢（开玩笑，千万别！）
### 留个邮箱
203882180@qq.com
这很重要. 为了让我们能方便的联系到你.
为了保护隐私, 你可以邮将此issue的地址和你的信息发送到join_think_spirit@yuzhes.com, 我们会单独核实

**Comment by qwertycxz** [comment]
👍

**Comment by bkmashiro** [comment]
lgtm
