### ISSUE TITLE
Appliance to DevTeam of Goodmarkets 2020

### ISSUE THREAD

**Issue by Goodmarkets** [ThinkSpiritLab/WeNeedYou#5]
## 自我介绍

马柯，计算机科学与技术，18级

### 使用的编程语言

|语言|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|C/C++|两年|控制台应用程序|熟悉|
|Java|一年|Web后端|应用|
|JavaScript|一年|Web前端|应用|

### 技术栈

|名称|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|HTML|一年|前端|应用|
|CSS|一年|前端|应用|
|JQuery|一年|前端|应用|
|React|半年|前端|了解|
|Servlet|半年|后端|应用|
|Spring Boot|半年|后端|了解|
|Nginx&Apache|半年|Web服务器|应用|
|MySQL|半年|数据库|熟悉|
|Linux|一年|部署|了解|

## 做过的项目

只有一些demo级别的东西，基本没啥。

## 加入后想做的项目

都行吧，可能偏向后端一点点，毕竟我比较闲。

## 指向个人主页、博客和/或仓库的链接 （如有）

博客写的比较东西比较隐私就不贴啦。

## 其他非你不可的理由

好像也没啥特别不可或缺的吧，就是对开发比较感兴趣。

**Comment by Nugine** [comment]
我觉得可以。顺便问一下做过的 demo 是什么，能用一两句话介绍一下吗？

**Comment by Goodmarkets** [comment]
就是学各种框架等东西的时候，会写一点用到它的东西。

**Comment by A0nameless0man** [comment]
> 就是学各种框架等东西的时候，会写一点用到它的东西。

那么，有没有可以展示的代码片呢？

**Comment by Goodmarkets** [comment]
> > 就是学各种框架等东西的时候，会写一点用到它的东西。
> 
> 那么，有没有可以展示的代码片呢？

没有什么特别值得展示的，都没有成一个系统，只是用到某方面内容而已。
