### ISSUE TITLE
Appliance to DevTeam of Moying 2020

### ISSUE THREAD

**Issue by Moying-moe** [ThinkSpiritLab/WeNeedYou#6]
## 自我介绍

姚润，18级，计软院，因为冲击计算机科学专业失败，滑档到物联网。
从小学接触编程，从中学开始对编程感兴趣并开始自学，从而产生浓厚兴趣，最后选择了计算机专业。
在大学才开始接触算法，比起算法更喜欢开发。喜欢利用自己开发的工具方便自己的生活。

### 使用的编程语言

|语言|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|C++|2年|控制台应用程序 辅助python进行高CPU密度的运算|熟悉|
|Python|5年|后端、小工具、数据处理、爬虫、人工智能|精通|
|JavaScript|1年|html+js、无后端web应用或对接后端|应用|

### 技术栈

|名称|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|HTML|2年|前端，主要开发方便朋友/自己的小工具|应用|
|CSS|2年|前端|应用|
|JQuery|1年|前端|熟悉|
|VueJs|1年|前端|熟悉|
|Flask|1年|后端|应用|
|Nginx|1年|服务器配置|了解|
|Linux|1年|部署比较简单的应用 只接触过centos7|了解|
|MySQL|0.5年|数据库|了解|
|Github|0.5年|保留自己的优秀作品或脑洞|了解|
|pytorch|近1年|随导师做项目 基本上已完成|熟悉|
|PS|3年|宣传、美工 任职于校级组织设计部|精通|
|PR|2年|宣传 同上|精通|
|AE|1年|宣传 同上|精通|

## 做过的项目

无大型项目，做过很多小工具。最大是一个UI比赛的项目(web端)。
制作的大部分小工具可以在[我的主页](http://moyingmoe.top/)里的**个人作品**中找到。

## 加入后想做的项目

OJ，后端前端都想做。但是在多年与一些大佬同学共同学习的过程中渐渐发现自己的算法天赋虽然还行但是并不顶尖，所以害怕自己会对非常底层的东西力不从心。

## 指向个人主页、博客和/或仓库的链接 （如有）

 - [个人主页](http://moyingmoe.top/)
 - [CSDN博客](http://blog.moyingmoe.top/) *近期没有更新*
 - 托管至github的项目：
     - [python数据可视化工具](https://github.com/Moying-moe/python_ranking_visualization_based_on_pygame)
     - [基于旧版TSOJ的PC版OJ](https://github.com/Moying-moe/python_tsoj_for_windows) *因为TSOJ版本更新API变动已经失效*
     - [python_俄罗斯方块](https://github.com/Moying-moe/python_pygame_tetris)

## 其他非你不可的理由

我对编程、开发有非常浓厚的兴趣，对于我来说，写代码和玩游戏都是我娱乐的一种方式。在大一时我曾经与当时管理TSOJ的学长有过交流、提过一些建议，并在当时产生了想要加入OJ开发组的想法——即便我还有许多学的不够深的地方。在过去的5年，我一直习惯于独立开发，所以我很渴望能够有一次在团队中一起努力、相互协作的经历。

**Comment by Nugine** [comment]
可以作为外部协作者 (outside collaborators) 加入。
@A0nameless0man
