### ISSUE TITLE
Appliance to DevTeam of fordring 2020

### ISSUE THREAD

**Issue by trionfordring** [ThinkSpiritLab/WeNeedYou#7]
## 自我介绍

项佳宇，计算机类，19级

### 使用的编程语言

|语言|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|JAVA|4年|主力语言,后端,控制台程序,GUI|熟练|
|C/C++|3年|控制台程序,windows.h|应用|
|HTML/CSS/JS|3年|前端页面|应用|
|C#|3年|UNITY开发|熟悉|
|Python|3年|草稿纸|了解|
|GOLANG|0年|好久没写，基本忘了|了解|

### 技术栈

|名称|时长|用途|程度|
|:-:|:-:|:-:|:-:|
|SPRING全家桶|3年|包括security,shell,mail,data-jpa等，以及spring-cloud的常用组件|熟练|
|MYSQL|3年|存储数据，基本隔着框架和它打交道|了解|
|hibernate|3年|几年以前用过，现在隔着spring-data-jpa|了解|
|SLF4J|3年|这也算技术？我精通log.info好趴。|应用|
|Unity|3年|复制过一些小游戏|应用|
|Linux|3年|ls cd|了解|
|JQuery|3年|基本操作，动画|应用|
|Tomcat|3年|以前单独使用，现在嵌入spring-boot中使用|应用|
|Nginx|3年|请求转发|了解|
|node.js|1年|使用过此平台的一些轮子|了解|
|electron|1年|gui|了解|
|frp|0年|内网穿透快速开放项目到公网，超方便|应用|
|VUE|0年|正在学习|了解|

### 5.6日  `5.6日更新`

写了一个c++的2048 
https://github.com/trionfordring/CppGames   
releases: https://gitee.com/trionfordring/CppGames/releases

### 一个月前

基于spring-security的一个实现登入登出的没吊用但是好看的网站，用于前端练手。  
https://gitee.com/trionfordring/Demos/tree/master/user-login  

### 三个月前

一个用户高达35人的投票小网站，实现了用户登入上传图像和投票（班级群头评选）  
https://github.com/trionfordring/nuist-6-voter

### 两年前

很多不值一提的小demo,基本遗失

## 加入后想做的项目

任何，话说也没说有什么项目可以做吧

## 指向个人主页、博客和/或仓库的链接 （如有）

https://gitee.com/trionfordring

**Comment by Nugine** [comment]
有项目想法可以提议，写一写创意和设计即可。目前还没有想好做啥。
我这边 Accepted.
@A0nameless0man
